{{- $outer := . }}
{{- range $name, $deployment := .Values.deployments }}
{{- with $outer }}
{{- if gt (int (toString $deployment.replicaCount)) 0 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "trackableappname" . }}-{{ $name }}
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service }}
    deployment-type: {{ $name }}
spec:
  selector:
    matchLabels:
      app: {{ template "appname" . }}
      track: "{{ .Values.application.track }}"
      tier: "{{ .Values.application.tier }}"
      release: {{ .Release.Name }}
      deployment-type: {{ $name }}
  replicas: {{ $deployment.replicaCount }}
{{ if .Values.strategyType }}
  strategy:
    type: {{ .Values.strategyType | quote }}
{{ end }}
  template:
    metadata:
      annotations:
        checksum/application-secrets: "{{ .Values.application.secretChecksum }}"
      labels:
        app: {{ template "appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        release: {{ .Release.Name }}
        deployment-type: {{ $name }}
    spec:
      imagePullSecrets:
{{ toYaml $deployment.image.secrets | indent 8 }}
      containers:
      - name: {{ template "trackableappname" . }}-pod
        image: "{{ $deployment.image.repository }}:{{ $deployment.image.tag }}"
        imagePullPolicy: {{ $deployment.image.pullPolicy }}
{{ if .Values.application.secretName }}
        envFrom:
        - secretRef:
            name: {{ .Values.application.secretName }}
{{ end }}
        env:
        - name: GITLAB_ENVIRONMENT_NAME
          value: {{ .Values.gitlab.envName }}
        - name: GITLAB_ENVIRONMENT_URL
          value: {{ .Values.gitlab.envURL }}
        ports:
        - name: "{{ .Values.service.name }}"
          containerPort: {{ .Values.service.internalPort }}
{{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
{{- end }}
{{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
{{- end }}
{{- end }}
